function [E, y, ybk, yfit] = geopixe_importfit(filename)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   HIGHEPBREG030UM0 = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   HIGHEPBREG030UM0 = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data
%   from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   HighEPbReg030um0 = importfile('HighE_PbReg0_30um_0.3mgcm2Top.csv', 2, 4322);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/11/09 16:18:37

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Create output variable
A = [dataArray{1:end-1}];
E=A(:,1);
y = A(:,2);
ybk = A(:,3);
yfit = A(:,4);

