% gid_setup.m

addpath('/home/aw30/Matlab/Gidview:', ...
     '/home/aw30/Matlab/Matlab_Xray_Utils/Analysis:', ...
     '/home/aw30/Matlab/Matlab_Xray_Utils/Energy_Calibration:', ...
     '/home/aw30/Matlab/Matlab_Xray_Utils/File_Handling:', ...
     '/home/aw30/Matlab/Matlab_Xray_Utils/One_time_scripts:', ...
     '/home/aw30/Matlab/Matlab_Xray_Utils/Openspec:', ...
     '/home/aw30/Matlab/Matlab_Xray_Utils/Plotting_GID:', ...
     '/home/aw30/Matlab/Matlab_Xray_Utils/Plotting_General:', ...
     '/home/aw30/Matlab/Matlab_Xray_Utils/Misc:')

% Setup Plotting defaults (from Plotting_General)
plotting_defaults

% define Bragg Calcs (from Misc)
bragg_calcs

