% gid_setup.m
addpath([AW_MATLAB_BASE 'Gidview'], ...
     [AW_MATLAB_BASE 'Matlab_Xray_Utils/Analysis'], ...
     [AW_MATLAB_BASE 'Matlab_Xray_Utils/Energy_Calibration'], ...
     [AW_MATLAB_BASE 'Matlab_Xray_Utils/File_Handling'], ...
     [AW_MATLAB_BASE 'Matlab_Xray_Utils/One_time_scripts'],...
     [AW_MATLAB_BASE 'Matlab_Xray_Utils/Openspec'], ...
     [AW_MATLAB_BASE 'Matlab_Xray_Utils/Plotting_GID'], ...
     [AW_MATLAB_BASE 'Matlab_Xray_Utils/Plotting_General'], ...
     [AW_MATLAB_BASE 'Matlab_Xray_Utils/Misc'])

% define Bragg Calcs (from Misc)
bragg_calcs

