% mcaview_setup.m

addpath([AW_MATLAB_BASE 'Mcaview:'], ...
     [AW_MATLAB_BASE 'Matlab_Xray_Utils/Analysis:'], ...
     [AW_MATLAB_BASE 'Matlab_Xray_Utils/Energy_Calibration:'], ...
     [AW_MATLAB_BASE 'Matlab_Xray_Utils/Openspec:'], ...
     [AW_MATLAB_BASE 'Matlab_Xray_Utils/Plotting_General:'])
